#+TITLE: Accounting
#+AUTHOR:
#+OPTIONS: tex:t
#+STARTUP: latexpreview
#+latex_class_options: [a4paper, 12pt]
#+LATEX_HEADER: \pdfpkresolution=300
#+LATEX_HEADER: \usepackage[margin=1.5cm]{geometry}

* Accounting terms
** Book keeping
- Book keeping is the process of recording business transactions into a set of
books.
- Only transactions of monetary value are found in this book.
- These transactions represent the transfer of economic value from one entity to
  another.
- It is also referred to as a set of primary records.
- It is an /art/.
** Financial Accounting
According to Indian General Accepted Accounting Principles(GAAP),it is the
procedure of recording, reporting transactions of monetary nature for statutory
requirements.
*** General procedure:
1. All business transactions are recorded in the form of *Journal Entries* on the
   basis of the [[Golden Rule of Accounting][golden rule of accounting]].
2. Transactions of similar nature are grouped together and compiled into a *Ledger*.
3. Since there are a lot of transactions in the ledger, the ledger is then
   summarized into a *Trial Balance* and then reported in the form of *Financial Statements*.
*** Composition of Financial Statement
It comprises of 3 statements:
1. Statement of Income and Gains & Expenditures and Losses (PnL Report).
   - Recorded for a *financial year* (1^{st} April to 31^{st} March in India)
2. Statement of Sources & Application of Funds (Balance Sheet).
   - Recorded since the start of the company.
3. Fund flow statement.
   - It analyses a company’s Balance Sheet of two years to validate the movement
     of funds from the previous financial year to the current year. (copied this
     definition from the internet)
   - It compares the source of inflow and outflow of funds during the concerned
     accounting period and analyses how it affects the working
     capital of an organization.
*** Golden Rule of Accounting
_Debit what comes in, credit what goes out_.
Debit the receiver, credit the giver.
** Cost Accounting
Cost accounting is the technique of recording and analyzing the goods and services
produced and reporting it to the internal decision makers.
** Management Accounting
The *set of tools* required to assess certain parameters to determine the business
performance, in order to report it to the internal decision makers(management)
for planning, evaluating and controlling their resources.
** Accounting cycle
Recordings transactions \to Journal \to Ledger \to Trial Balance \to Adjustment entries \to
Adjustment Trial Balance \to Closing Entries \to Financial Statement \to Recording Transactions

* Objectives of accounting
1. To obtain the amount of Profits and Losses made by the business.
2. To know the financial Position of the business.
3. To provide a record for compliance with statutes and applicable laws.
4. To disclose financial information to the internal and external decision makers.
* Balance sheet terms
** Owner's Liability
The contributions made by the owner (equity shareholders) to the business.
*** Owner's Capital
- The net profit made (residual assets) belong to the owners(equity shareholders),
since they are the residual claimers.
- These profits can be distributed amongst the shareholdes in the form of *dividends*,
  or retain the amount for future investments called *retained earnings*.
*** Net worth
net worth = equity capital provided by owners + reserves and surpluses
** Creditor's Liability
*** Short Term/Current Liability
Loan is taken from bank and goods are bought on credit.
|-------------------------------------------------------------------+----------------------------------------------------------------------------|
| *Owner's Liability*                                                 | *Creditor's Liability*                                                       |
|-------------------------------------------------------------------+----------------------------------------------------------------------------|
| The business may not necessarily have to pay the original amount. | The business is obligated to repay the capital amount along with interest. |
|-------------------------------------------------------------------+----------------------------------------------------------------------------|
| The interest amount may vary, or there may be no interest at all. | The interest amount is specified at  the time of the original investment.  |
|-------------------------------------------------------------------+----------------------------------------------------------------------------|
A liability shall be classified as current when it satisfies any one of the following:
1. It is expected to be settled in the company's *normal operating cycle*. (generally <1 year)
2. It is held mainly for the purpose of *trading*.
3. It is due to be settled within 12 months after the reporting date.
4. The company does not have an unconditional right to defer settlement of the
   liability for /atleast/ 12 months after the reporting data.
**** Significance
- It shows the liquidity position of the company (ability to pay vs. willingness
to pay)
- *Example*: Account payable; expense outstanding.
**** Note
It is not necessary that if the current liabilities of the company are increasing,
then the liquidity position of the company is bad. There are many instances
wherein the *bargaining power* of the company proves to be a valuable resource for
the company.
*** Long Term/Non-current Liability
All other liabilities fall under this category. E.g. Loan taken for 5 years,
Debentures issued, etc.

** Contingent Liability
It represents a *potential obligation* that could be created depending on the
outcome of an event.
